backend:
  name: git-gateway
  branch: main # Use 'main' or 'master' depending on your GitHub repository

media_folder: "media/uploads" 
public_folder: "/media/uploads"

collections:
  - name: "library"
    label: "Video Library"
    label_singular: "Entry"
    file: "js/videos.json" # The CMS will directly edit this file
    extension: "json"
    format: "json"
    create: true
    slug: "{{id}}"
    widget: "list"
    fields:
      - { label: "Unique ID (all lowercase, use dashes, e.g., 'hidden-love')", name: "id", widget: "string" }
      - { label: "Type", name: "type", widget: "select", options: ["movie", "drama", "anime"] }
      - { label: "Subcategory (e.g., Bollywood, Korean)", name: "subcategory", widget: "string" }
      - { label: "IMDb ID (e.g., tt1234567)", name: "imdb_id", widget: "string" }
      - { label: "Google Drive ID (for single Movies only)", name: "google_drive_id", widget: "string", required: false }
      - label: "Seasons (for Dramas and Animes)"
        name: "seasons"
        widget: "list"
        required: false
        fields:
          - { label: "Season Title (e.g., Season 1)", name: "season_title", widget: "string" }
          - label: "Episodes"
            name: "episodes"
            widget: "list"
            fields:
              - { label: "Episode Title", name: "title", widget: "string" }
              - { label: "Episode Google Drive ID", name: "google_drive_id", widget: "string" }